before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - rustc src/httpc/lib.rs
  - rustc --test src/httpc/lib.rs
  - ./httpc
notifications:
  email:
    recipients:
      - fledna@foxmail.com
    on_success: change
    on_failure: always
