before_install:
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
install:
  - sudo ./rust-nightly-x86_64-unknown-linux-gnu/install.sh
script:
  - rustc src/httpc/lib.rs
  - rustc --test src/httpc/lib.rs
  - ./httpc
notifications:
  email:
    recipients:
      - fledna@foxmail.com
    on_success: change
    on_failure: always
